language: cpp
sudo: required

#whitelist
branches:
  only:
    - master
    - develop

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libasound2-dev
  - cd Project/Builds/Linux 

script: make

compiler: clang

os:
  - linux